### ISSUE TITLE
when running sample_legacy.py got error

### ISSUE THREAD

**Issue by fusu192** [shirobu2400/mmdpy#4]
C:\Users\xxx\Downloads\mmdpy-master\demo\miku>python sample_legacy.py -p 1.pmx -v SunnyDays.vmd --bone False
pybullet build time: Jun 28 2023 14:59:35
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\mmdpy-master\demo\miku\sample_legacy.py", line 157, in <module>
    main()
  File "C:\Users\xxx\Downloads\mmdpy-master\demo\miku\sample_legacy.py", line 129, in main
    glut.glutInit(sys.argv)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pyopengl-3.1.7-py3.10.egg\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pyopengl-3.1.7-py3.10.egg\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

**Comment by shirobu2400** [comment]
will close once
